version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src/
    tty: true
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - jaeger-example
    depends_on:
      - jaeger
  jaeger:
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - jaeger-example
networks:
  jaeger-example:
