receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4316

processors:
  filter:
    traces:
      span:
        - attributes["roll.value"]==2


exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter]
      exporters: [otlp/jaeger]

